[package]
name = "flaco"
version = "0.1.0"
edition = "2018"
license = "Unlicense/MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
tokio = { version = "^1.12", features = ["full"] }
tokio-postgres = "0.7.2"
tokio-postgres-rustls = "0.8.0"

[build-dependencies]
cbindgen = "^0.6.0"

[profile.dev]
lto = false
debug = true

[profile.release]
lto = true
debug = false
incremental = false
opt-level = 3