[package]
name = "flaco"
version = "0.1.0"
edition = "2018"
license = "Unlicense/MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["staticlib"]

[dependencies]
postgres = "0.19.1"
postgres-types = "0.2.1"

[build-dependencies]
cbindgen = "^0.6.0"

[profile.dev]
lto = false
debug = true

[profile.release]
lto = true
debug = false
incremental = false
opt-level = 3